In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from imblearn.over_sampling import ADASYN
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,confusion_matrix, roc_auc_score, classification_report

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/DATASETS/CIC-IDS-2017/final_df.csv')

In [ ]:
df.head(5)

,Destination Port,Total Length of Fwd Packets,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,...,min_seg_size_forward,Idle Std,Label,Active_Profile,Fwd Packet Length_Profile,Total Packets and Subflow Bwd Profile,Fwd Flow IAT Max and Idle Profile,Flow Duration Fwd IAT Total,Fwd Avg Segement and Packet Length Mean profile,Idle_Profile
0,3.135494,7.887959,976,0,5.069190,5.748358,7595.104640,67.122468,15075.50000,104051.399700,...,32,0.0,BENIGN,-210328.408018,14.721471,0.0,-1.636778e+07,1.0,2.079805,-1.617048e+07
1,3.135494,7.887959,976,0,5.069190,5.748358,7289.936810,64.425518,15706.58333,104861.870100,...,32,0.0,BENIGN,-210328.408018,14.721471,0.0,-1.636563e+07,1.0,2.079805,-1.617048e+07
2,3.135494,0.000000,0,0,0.000000,0.000000,0.000000,12500.000000,160.00000,0.000000,...,32,0.0,BENIGN,-210328.408018,0.000000,0.0,-1.693556e+07,160.0,-89.809584,-1.617048e+07
3,3.135494,7.911691,976,0,5.068605,5.768700,7182.267884,63.675308,15896.19512,106554.899000,...,32,0.0,BENIGN,-210328.408018,14.735923,0.0,-1.636514e+07,1.0,4.287358,-1.617048e+07
4,10.474382,0.000000,0,0,0.000000,0.000000,0.000000,38961.038960,38.50000,14.849242,...,32,0.0,BENIGN,-210328.408018,0.000000,0.0,-1.693559e+07,77.0,-89.809584,-1.617048e+07

In [ ]:
df.tail(5)

,Destination Port,Total Length of Fwd Packets,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,...,min_seg_size_forward,Idle Std,Label,Active_Profile,Fwd Packet Length_Profile,Total Packets and Subflow Bwd Profile,Fwd Flow IAT Max and Idle Profile,Flow Duration Fwd IAT Total,Fwd Avg Segement and Packet Length Mean profile,Idle_Profile
2520793,3.988984,4.727388,76,76,4.343805,0.0,8.194940e+03,186.248642,6443.0,13617.579480,...,20,0.0,BENIGN,-210328.408018,0.0,0.0,-1.691763e+07,1.044856,-50.211604,-1.617048e+07
2520794,3.988984,4.442651,181,181,5.204007,0.0,1.376543e+06,12345.679010,108.0,183.597386,...,20,0.0,BENIGN,-210328.408018,0.0,0.0,-1.693551e+07,162.000000,-30.412614,-1.617048e+07
2520795,10.968733,3.465736,6,6,1.945910,0.0,4.512195e+05,36585.365850,41.0,52.325902,...,32,0.0,BENIGN,-210328.408018,0.0,0.0,-1.693558e+07,20.500000,-67.889273,-1.617048e+07
2520796,3.988984,5.262690,128,128,4.859812,0.0,4.272221e+02,7.628965,149805.0,375521.040500,...,20,0.0,BENIGN,-210328.408018,0.0,0.0,-1.635113e+07,1.014533,-44.554750,-1.617048e+07
2520797,3.988984,5.241747,113,113,4.736198,0.0,4.360695e+03,63.198475,18987.8,31664.102560,...,20,0.0,BENIGN,-210328.408018,0.0,0.0,-1.689295e+07,1.299626,-23.341546,-1.617048e+07

In [ ]:
df.shape

(2520798, 46)

In [ ]:
df.columns

Index(['Destination Port', 'Total Length of Fwd Packets',
       'Bwd Packet Length Max', 'Bwd Packet Length Min',
       'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s',
       'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Min',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Min', 'Bwd IAT Total',
       'Bwd IAT Mean', 'Fwd PSH Flags', 'Fwd Header Length',
       'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s',
       'Min Packet Length', 'Max Packet Length', 'Packet Length Mean',
       'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count',
       'PSH Flag Count', 'ACK Flag Count', 'Down/Up Ratio',
       'Average Packet Size', 'Avg Bwd Segment Size', 'Subflow Fwd Bytes',
       'Init_Win_bytes_forward', 'Init_Win_bytes_backward', 'act_data_pkt_fwd',
       'min_seg_size_forward', 'Idle Std', 'Label', 'Active_Profile',
       'Fwd Packet Length_Profile', 'Total Packets and Subflow Bwd Profile',
       'Fwd Flow IAT Max and Idle Profile', 'Flow Duration Fwd IAT Total',
       'Fwd Avg Segement and Packet Length Mean profile', 'Idle_Profile'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2520798 entries, 0 to 2520797
Data columns (total 46 columns):
 #   Column                                           Dtype
---  ------                                           -----
 0   Destination Port                                 float64
 1   Total Length of Fwd Packets                      float64
 2   Bwd Packet Length Max                            int64
 3   Bwd Packet Length Min                            int64
 4   Bwd Packet Length Mean                           float64
 5   Bwd Packet Length Std                            float64
 6   Flow Bytes/s                                     float64
 7   Flow Packets/s                                   float64
 8   Flow IAT Mean                                    float64
 9   Flow IAT Std                                     float64
 10  Flow IAT Min                                     int64
 11  Fwd IAT Mean                                     float64
 12  Fwd IAT Std                                      float64
 13  Fwd IAT Min                                      int64
 14  Bwd IAT Total                                    int64
 15  Bwd IAT Mean                                     float64
 16  Fwd PSH Flags                                    int64
 17  Fwd Header Length                                float64
 18  Bwd Header Length                                int64
 19  Fwd Packets/s                                    float64
 20  Bwd Packets/s                                    float64
 21  Min Packet Length                                int64
 22  Max Packet Length                                float64
 23  Packet Length Mean                               float64
 24  Packet Length Std                                float64
 25  Packet Length Variance                           float64
 26  FIN Flag Count                                   int64
 27  PSH Flag Count                                   int64
 28  ACK Flag Count                                   int64
 29  Down/Up Ratio                                    int64
 30  Average Packet Size                              float64
 31  Avg Bwd Segment Size                             float64
 32  Subflow Fwd Bytes                                float64
 33  Init_Win_bytes_forward                           int64
 34  Init_Win_bytes_backward                          int64
 35  act_data_pkt_fwd                                 int64
 36  min_seg_size_forward                             int64
 37  Idle Std                                         float64
 38  Label                                            object
 39  Active_Profile                                   float64
 40  Fwd Packet Length_Profile                        float64
 41  Total Packets and Subflow Bwd Profile            float64
 42  Fwd Flow IAT Max and Idle Profile                float64
 43  Flow Duration Fwd IAT Total                      float64
 44  Fwd Avg Segement and Packet Length Mean profile  float64
 45  Idle_Profile                                     float64
dtypes: float64(29), int64(16), object(1)
memory usage: 884.7+ MB

In [ ]:
df.describe()

,Destination Port,Total Length of Fwd Packets,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,...,act_data_pkt_fwd,min_seg_size_forward,Idle Std,Active_Profile,Fwd Packet Length_Profile,Total Packets and Subflow Bwd Profile,Fwd Flow IAT Max and Idle Profile,Flow Duration Fwd IAT Total,Fwd Avg Segement and Packet Length Mean profile,Idle_Profile
count,2.520798e+06,2.520798e+06,2.520798e+06,2.520798e+06,2.520798e+06,2.520798e+06,2.520798e+06,2.520798e+06,2.520798e+06,2.520798e+06,...,2.520798e+06,2.520798e+06,2.520798e+06,2.520798e+06,2.520798e+06,2.520798e+06,2.520798e+06,2.520798e+06,2.520798e+06,2.520798e+06
mean,5.835174e+00,4.066319e+00,8.736795e+02,4.204104e+01,3.800702e+00,2.017483e+00,2.583066e+05,1.631162e+04,1.052209e+06,2.933552e+06,...,2.519529e+00,-3.082233e+03,4.275923e+03,-1.516655e+05,4.858089e+00,3.069699e-01,-1.028480e+06,8.076648e+03,-6.919057e+00,-1.033252e+06
std,2.482430e+00,2.275434e+00,1.669808e+03,6.192687e+01,2.518888e+00,3.081380e+00,6.025310e+05,3.881657e+04,2.209985e+06,7.000806e+06,...,4.639878e+00,1.149758e+06,1.584831e+04,1.722035e+05,1.176830e+01,1.821005e+00,4.025353e+07,1.884453e+04,2.102164e+02,3.941500e+07
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-2.610000e+08,-2.000000e+06,-1.300000e+01,0.000000e+00,...,0.000000e+00,-5.368707e+08,0.000000e+00,-2.103284e+05,0.000000e+00,0.000000e+00,-1.693561e+07,-1.300000e+01,-8.980958e+01,-1.617048e+07
25%,3.988984e+00,2.564949e+00,6.000000e+00,0.000000e+00,1.945910e+00,0.000000e+00,1.194308e+02,2.023326e+00,8.300000e+01,0.000000e+00,...,0.000000e+00,2.000000e+01,0.000000e+00,-2.103284e+05,0.000000e+00,0.000000e+00,-1.693555e+07,1.000000e+00,-8.132430e+01,-1.617048e+07
50%,4.394449e+00,4.204693e+00,9.700000e+01,0.000000e+00,4.494239e+00,0.000000e+00,3.715038e+03,6.974224e+01,2.044067e+04,1.239435e+04,...,1.000000e+00,2.000000e+01,0.000000e+00,-2.103284e+05,0.000000e+00,0.000000e+00,-1.691905e+07,3.687500e+00,-3.854434e+01,-1.617048e+07
75%,6.095825e+00,5.808142e+00,7.460000e+02,8.200000e+01,5.390273e+00,5.581278e+00,1.071429e+05,1.785714e+04,5.576706e+05,1.492018e+06,...,3.000000e+00,3.200000e+01,0.000000e+00,-2.103284e+05,0.000000e+00,0.000000e+00,-1.404692e+07,2.676667e+02,-1.627048e+01,-1.617048e+07
max,1.109035e+01,1.637274e+01,5.792000e+03,2.520000e+02,8.665872e+00,9.011360e+00,2.008811e+06,1.538462e+05,7.755745e+06,2.570000e+07,...,2.900000e+01,1.380000e+02,6.863040e+04,4.868900e+05,1.581253e+02,2.064738e+01,1.302724e+08,6.898200e+04,1.786098e+03,1.308586e+08

In [ ]:
df.isnull().sum()

Destination Port                                   0
Total Length of Fwd Packets                        0
Bwd Packet Length Max                              0
Bwd Packet Length Min                              0
Bwd Packet Length Mean                             0
Bwd Packet Length Std                              0
Flow Bytes/s                                       0
Flow Packets/s                                     0
Flow IAT Mean                                      0
Flow IAT Std                                       0
Flow IAT Min                                       0
Fwd IAT Mean                                       0
Fwd IAT Std                                        0
Fwd IAT Min                                        0
Bwd IAT Total                                      0
Bwd IAT Mean                                       0
Fwd PSH Flags                                      0
Fwd Header Length                                  0
Bwd Header Length                                  0
Fwd Packets/s                                      0
Bwd Packets/s                                      0
Min Packet Length                                  0
Max Packet Length                                  0
Packet Length Mean                                 0
Packet Length Std                                  0
Packet Length Variance                             0
FIN Flag Count                                     0
PSH Flag Count                                     0
ACK Flag Count                                     0
Down/Up Ratio                                      0
Average Packet Size                                0
Avg Bwd Segment Size                               0
Subflow Fwd Bytes                                  0
Init_Win_bytes_forward                             0
Init_Win_bytes_backward                            0
act_data_pkt_fwd                                   0
min_seg_size_forward                               0
Idle Std                                           0
Label                                              0
Active_Profile                                     0
Fwd Packet Length_Profile                          0
Total Packets and Subflow Bwd Profile              0
Fwd Flow IAT Max and Idle Profile                  0
Flow Duration Fwd IAT Total                        0
Fwd Avg Segement and Packet Length Mean profile    0
Idle_Profile                                       0
dtype: int64

In [ ]:
def countduplicate(df):
    duplicate_count=df.duplicated().sum()
    print(f" The number of the duplicated rows in the dataset is  {duplicate_count} amounting to the {(duplicate_count/len(df))*100 : .2f}% of total")

In [ ]:
countduplicate(df)

 The number of the duplicated rows in the dataset is  5207 amounting to the  0.21% of total

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.shape

(2515591, 46)

In [ ]:
df['Label'].value_counts()

Label
BENIGN                        2089851
DoS Hulk                       172846
DDoS                           128014
PortScan                        90694
DoS GoldenEye                   10286
FTP-Patator                      5931
DoS slowloris                    5385
DoS Slowhttptest                 5227
SSH-Patator                      3219
Bot                              1948
Web Attack � Brute Force         1470
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name: count, dtype: int64

In [ ]:
le=LabelEncoder()
x=df.drop('Label',axis=1)
y=df['Label']

In [ ]:
y=le.fit_transform(y)

In [ ]:
from collections import Counter

In [ ]:
c=Counter(y)
for k in c.keys():
  print(k, c[k])

0 2089851
10 90694
12 1470
14 652
13 21
7 5931
11 3219
2 128014
1 1948
9 36
6 5385
5 5227
4 172846
3 10286
8 11

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42, stratify=y)

In [ ]:
train_class_counts = Counter(y_train)
print("Original training class distribution:", train_class_counts)
sampling_strategy = {}
for class_label, count in train_class_counts.items():
    if count < 100:
        sampling_strategy[class_label] = count * 30
adasyn = ADASYN(sampling_strategy=sampling_strategy, random_state=42, n_neighbors=5)
x_resampled, y_resampled = adasyn.fit_resample(x_train, y_train)
print("Resampled class distribution:", Counter(y_resampled))

Original training class distribution: Counter({np.int64(0): 1567388, np.int64(4): 129634, np.int64(2): 96010, np.int64(10): 68021, np.int64(3): 7715, np.int64(7): 4448, np.int64(6): 4039, np.int64(5): 3920, np.int64(11): 2414, np.int64(1): 1461, np.int64(12): 1103, np.int64(14): 489, np.int64(9): 27, np.int64(13): 16, np.int64(8): 8})
Resampled class distribution: Counter({np.int64(0): 1567388, np.int64(4): 129634, np.int64(2): 96010, np.int64(10): 68021, np.int64(3): 7715, np.int64(7): 4448, np.int64(6): 4039, np.int64(5): 3920, np.int64(11): 2414, np.int64(1): 1461, np.int64(12): 1103, np.int64(9): 808, np.int64(14): 489, np.int64(13): 483, np.int64(8): 240})

In [ ]:
del y_train

In [ ]:
y_train = y_resampled

In [ ]:
del x_train

In [ ]:
x_train=x_resampled

In [ ]:
y_train=le.inverse_transform(y_train)

In [ ]:
c2=Counter(y_train)
print(c2)

Counter({'BENIGN': 1567388, 'DoS Hulk': 129634, 'DDoS': 96010, 'PortScan': 68021, 'DoS GoldenEye': 7715, 'FTP-Patator': 4448, 'DoS slowloris': 4039, 'DoS Slowhttptest': 3920, 'SSH-Patator': 2414, 'Bot': 1461, 'Web Attack � Brute Force': 1103, 'Infiltration': 808, 'Web Attack � XSS': 489, 'Web Attack � Sql Injection': 483, 'Heartbleed': 240})

In [ ]:
c3=Counter(y_test)
print(c3)

Counter({np.int64(0): 522463, np.int64(4): 43212, np.int64(2): 32004, np.int64(10): 22673, np.int64(3): 2571, np.int64(7): 1483, np.int64(6): 1346, np.int64(5): 1307, np.int64(11): 805, np.int64(1): 487, np.int64(12): 367, np.int64(14): 163, np.int64(9): 9, np.int64(13): 5, np.int64(8): 3})

In [ ]:
y_test=le.inverse_transform(y_test)

In [ ]:
c4=Counter(y_test)
print(c4)

Counter({'BENIGN': 522463, 'DoS Hulk': 43212, 'DDoS': 32004, 'PortScan': 22673, 'DoS GoldenEye': 2571, 'FTP-Patator': 1483, 'DoS slowloris': 1346, 'DoS Slowhttptest': 1307, 'SSH-Patator': 805, 'Bot': 487, 'Web Attack � Brute Force': 367, 'Web Attack � XSS': 163, 'Infiltration': 9, 'Web Attack � Sql Injection': 5, 'Heartbleed': 3})

In [ ]:
label_mapping = {label: idx for idx, label in enumerate(le.classes_)}
print(label_mapping)

{'BENIGN': 0, 'Bot': 1, 'DDoS': 2, 'DoS GoldenEye': 3, 'DoS Hulk': 4, 'DoS Slowhttptest': 5, 'DoS slowloris': 6, 'FTP-Patator': 7, 'Heartbleed': 8, 'Infiltration': 9, 'PortScan': 10, 'SSH-Patator': 11, 'Web Attack � Brute Force': 12, 'Web Attack � Sql Injection': 13, 'Web Attack � XSS': 14}

In [ ]:
rf = RandomForestClassifier(random_state=42, n_jobs=-1)
rf.fit(x_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [ ]:
y_pred = rf.predict(x_test)
y_proba = rf.predict_proba(x_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
class_report = classification_report(y_test, y_pred)
auc_roc = roc_auc_score(y_test, y_proba, multi_class='ovr')

In [ ]:
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("AUC-ROC Score:", auc_roc)
print("\nClassification Report:\n", class_report)

Accuracy: 0.9982063864092429
Precision: 0.9981533405941103
Recall: 0.9982063864092429
F1 Score: 0.998171866574107
AUC-ROC Score: 0.9953756193482851

Classification Report:
                             precision    recall  f1-score   support

                    BENIGN       1.00      1.00      1.00    522463
                       Bot       0.87      0.75      0.80       487
                      DDoS       1.00      1.00      1.00     32004
             DoS GoldenEye       1.00      0.99      1.00      2571
                  DoS Hulk       1.00      1.00      1.00     43212
          DoS Slowhttptest       0.99      0.99      0.99      1307
             DoS slowloris       1.00      0.99      1.00      1346
               FTP-Patator       1.00      1.00      1.00      1483
                Heartbleed       1.00      1.00      1.00         3
              Infiltration       1.00      0.56      0.71         9
                  PortScan       0.99      0.99      0.99     22673
               SSH-Patator       1.00      0.99      1.00       805
  Web Attack � Brute Force       0.72      0.78      0.75       367
Web Attack � Sql Injection       0.00      0.00      0.00         5
          Web Attack � XSS       0.40      0.28      0.33       163

                  accuracy                           1.00    628898
                 macro avg       0.86      0.82      0.84    628898
              weighted avg       1.00      1.00      1.00    628898

In [ ]:
y_train_enc = le.transform(y_train)
y_test_enc = le.transform(y_test)

In [ ]:
xgb_model = XGBClassifier(
    objective='multi:softprob',
    num_class=len(le.classes_),
    use_label_encoder=False,
    eval_metric='mlogloss',
    n_jobs=-1,
    random_state=42
)

xgb_model.fit(x_train, y_train_enc)

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [05:44:01] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=-1, num_class=15, num_parallel_tree=None, ...)

In [ ]:
y_pred_enc = xgb_model.predict(x_test)
y_pred = le.inverse_transform(y_pred_enc)

y_proba = xgb_model.predict_proba(x_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision (macro):", precision_score(y_test, y_pred, average='macro'))
print("Recall (macro):", recall_score(y_test, y_pred, average='macro'))
print("F1 Score (macro):", f1_score(y_test, y_pred, average='macro'))
print("AUC-ROC Score:", roc_auc_score(y_test_enc, y_proba, multi_class='ovr'))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9988233386018083
Precision (macro): 0.8967274036729278
Recall (macro): 0.8647166908283757
F1 Score (macro): 0.8767185530805673
AUC-ROC Score: 0.9989696513362354

Classification Report:
                             precision    recall  f1-score   support

                    BENIGN       1.00      1.00      1.00    522463
                       Bot       0.91      0.75      0.82       487
                      DDoS       1.00      1.00      1.00     32004
             DoS GoldenEye       1.00      1.00      1.00      2571
                  DoS Hulk       1.00      1.00      1.00     43212
          DoS Slowhttptest       0.99      0.99      0.99      1307
             DoS slowloris       1.00      0.99      1.00      1346
               FTP-Patator       1.00      1.00      1.00      1483
                Heartbleed       1.00      1.00      1.00         3
              Infiltration       0.83      0.56      0.67         9
                  PortScan       0.99      1.00      0.99     22673
               SSH-Patator       1.00      1.00      1.00       805
  Web Attack � Brute Force       0.72      0.84      0.77       367
Web Attack � Sql Injection       0.60      0.60      0.60         5
          Web Attack � XSS       0.41      0.25      0.31       163

                  accuracy                           1.00    628898
                 macro avg       0.90      0.86      0.88    628898
              weighted avg       1.00      1.00      1.00    628898

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(x_train, y_train_enc)

y_pred_dt = dt_model.predict(x_test)
y_pred_dt_decoded = le.inverse_transform(y_pred_dt)

accuracy = accuracy_score(y_test, y_pred_dt_decoded)
classification_rep = classification_report(y_test, y_pred_dt_decoded)
conf_matrix = confusion_matrix(y_test, y_pred_dt_decoded)
precision = precision_score(y_test, y_pred_dt_decoded, average='macro', zero_division=0)
recall = recall_score(y_test, y_pred_dt_decoded, average='macro', zero_division=0)
y_prob_dt = dt_model.predict_proba(x_test)
auc_roc = roc_auc_score(y_test_enc, y_prob_dt, multi_class='ovr')

print(f"Accuracy: {accuracy}")
print("\nClassification Report (Macro):")
print(classification_rep)
print(f"\nPrecision (Macro): {precision}")
print(f"Recall (Macro): {recall}")
print(f"AUC-ROC Score: {auc_roc}")

Accuracy: 0.9980171665357498

Classification Report (Macro):
                            precision    recall  f1-score   support

                    BENIGN       1.00      1.00      1.00    522463
                       Bot       0.83      0.82      0.83       487
                      DDoS       1.00      1.00      1.00     32004
             DoS GoldenEye       0.99      0.99      0.99      2571
                  DoS Hulk       1.00      1.00      1.00     43212
          DoS Slowhttptest       0.98      0.99      0.98      1307
             DoS slowloris       0.99      0.99      0.99      1346
               FTP-Patator       1.00      1.00      1.00      1483
                Heartbleed       1.00      1.00      1.00         3
              Infiltration       0.56      0.56      0.56         9
                  PortScan       0.99      0.98      0.99     22673
               SSH-Patator       1.00      1.00      1.00       805
  Web Attack � Brute Force       0.72      0.72      0.72       367
Web Attack � Sql Injection       0.33      0.20      0.25         5
          Web Attack � XSS       0.38      0.38      0.38       163

                  accuracy                           1.00    628898
                 macro avg       0.85      0.84      0.85    628898
              weighted avg       1.00      1.00      1.00    628898


Precision (Macro): 0.8514464112594059
Recall (Macro): 0.8412850181502326
AUC-ROC Score: 0.9206154681518196

In [ ]:
from sklearn.ensemble import VotingClassifier
voting_clf = VotingClassifier(
    estimators=[('xgb', xgb_model), ('rf', rf)],
    voting='soft',
    n_jobs=-1
)

voting_clf.fit(x_train, y_train_enc)

y_pred_enc = voting_clf.predict(x_test)
y_pred_proba = voting_clf.predict_proba(x_test)

y_pred = le.inverse_transform(y_pred_enc)
y_test_decoded = le.inverse_transform(y_test_enc)

accuracy = accuracy_score(y_test_decoded, y_pred)
precision = precision_score(y_test_decoded, y_pred, average='macro', zero_division=0)
recall = recall_score(y_test_decoded, y_pred, average='macro', zero_division=0)
f1 = f1_score(y_test_decoded, y_pred, average='macro', zero_division=0)
auc_roc = roc_auc_score(y_test_enc, y_pred_proba, multi_class='ovr')

print("Ensemble Model Performance (Soft Voting):")
print(f"Accuracy: {accuracy}")
print(f"Precision (macro): {precision}")
print(f"Recall (macro): {recall}")
print(f"F1 Score (macro): {f1}")
print(f"AUC-ROC Score: {auc_roc}\n")
print("Classification Report:\n")
print(classification_report(y_test_decoded, y_pred))

📊 Ensemble Model Performance (Soft Voting):
Accuracy: 0.9987788162786334
Precision (macro): 0.886745773435742
Recall (macro): 0.8512659114748504
F1 Score (macro): 0.8648449715814788
AUC-ROC Score: 0.999765340515425

Classification Report:

                            precision    recall  f1-score   support

                    BENIGN       1.00      1.00      1.00    522463
                       Bot       0.90      0.78      0.83       487
                      DDoS       1.00      1.00      1.00     32004
             DoS GoldenEye       1.00      1.00      1.00      2571
                  DoS Hulk       1.00      1.00      1.00     43212
          DoS Slowhttptest       0.99      0.99      0.99      1307
             DoS slowloris       1.00      0.99      1.00      1346
               FTP-Patator       1.00      1.00      1.00      1483
                Heartbleed       1.00      1.00      1.00         3
              Infiltration       0.83      0.56      0.67         9
                  PortScan       0.99      1.00      0.99     22673
               SSH-Patator       1.00      1.00      1.00       805
  Web Attack � Brute Force       0.71      0.83      0.77       367
Web Attack � Sql Injection       0.50      0.40      0.44         5
          Web Attack � XSS       0.39      0.23      0.29       163

                  accuracy                           1.00    628898
                 macro avg       0.89      0.85      0.86    628898
              weighted avg       1.00      1.00      1.00    628898

In [ ]:
import joblib
from google.colab import files
joblib.dump(voting_clf, "ensemble_model.pkl")
files.download("ensemble_model.pkl")